-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█

-- █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = 1,
})

-- █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█

-- █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("waypaper --restore")
	hl.exec_cmd("fcitx5 -d")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("wl-clip-persist --clipboard regular --all-mime-type-regex '(?i)^(?!image/x-inkscape-svg).+'")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("wl-paste --watch pkill -RTMIN+9 waybar")
	hl.exec_cmd(
		"swayidle -w timeout 300 'swaylock -f -c 000000 --show-failed-attempts --fade-in 0.2 --grace 5 --grace-no-mouse --effect-vignette 0.5:0.5 --effect-blur 7x5 --ignore-empty-password --screenshots --clock' timeout 600 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' timeout 900 'systemctl suspend'"
	)
	hl.exec_cmd("playerctld daemon")
end)

-- █▀▀ █▄░█ █░█

-- ██▄ █░▀█ ▀▄▀

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

hl.env("QT_QPA_PLATFORMTHEME", "gtk3")

hl.env("QT_QPA_PLATFORMTHEME_QT6", "gtk3")

hl.env("TERMINAL", "kitty")

-- █ █▄░█ █▀█ █░█ ▀█▀

-- █ █░▀█ █▀▀ █▄█ ░█░

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
	input = {
		kb_layout = "us",
		numlock_by_default = true,
	},
})

-- ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█

-- █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█

-- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

hl.config({
	animations = {
		enabled = true,
	},
})

-- █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀

-- █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█

hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},
})

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
	dwindle = {
		preserve_split = true,
	},
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
	master = {
		mfact = 0.5,
	},
})

-- █▀▄▀█ █ █▀ █▀▀

-- █░▀░█ █ ▄█ █▄▄

-- See https://wiki.hyprland.org/Configuring/Variables/ for more

hl.config({
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		vrr = 1,
	},
})

-- █▀ █▀█ █░█ █▀█ █▀▀ █▀▀

-- ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄

-- Source a file (multi-file configs)

require("windowrules")
require("keybindings")
require("theme")
require("dms/colors") -- 路径需与你实际文件位置一致
