-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀

-- █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more
--
-- Set programs that you use

local terminal = "kitty"

-- $fileManager = pcmanfm-qt

local fileManager = "thunar"

local browser = "google-chrome-stable"

local code = "code"

-- $menu = rofi -show combi -combi-modi "drun,run" -show-icons -hover-select -me-select-entry '' -me-accept-entry !MousePrimary

local menu = "fuzzel"

local locking =
	"swaylock -f -c 000000 --show-failed-attempts --fade-in 0.2 --grace 5 --grace-no-mouse --effect-vignette 0.5:0.5 --effect-blur 7x5 --ignore-empty-password --screenshots --clock"

local mainMod = "SUPER"

hl.bind(
	mainMod .. " + " .. "SHIFT" .. " + " .. "E",
	hl.dsp.submap(" (l)锁定 (e)注销 (r)重启 (u)睡眠 (s)关机")
)

hl.define_submap(" (l)锁定 (e)注销 (r)重启 (u)睡眠 (s)关机", function()
	hl.bind("L", hl.dsp.exec_cmd(locking))
	hl.bind("L", hl.dsp.submap("reset"))
	hl.bind("E", hl.dsp.exit())
	hl.bind("R", hl.dsp.exec_cmd("systemctl reboot"))
	hl.bind("U", hl.dsp.exec_cmd("systemctl suspend"))
	hl.bind("U", hl.dsp.submap("reset"))
	hl.bind("S", hl.dsp.exec_cmd("systemctl poweroff"))
	hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.bind("print", hl.dsp.submap("󰄄 Pick (p) Output (o)+ Shift for "))

hl.define_submap("󰄄 Pick (p) Output (o)+ Shift for ", function()
	hl.bind(
		"P",
		hl.dsp.exec_cmd(
			"grimblast save area-| swappy -f- && [[ $(wl-paste -l)==image/png ]] && notify-send Screenshot copied to clipboard"
		)
	)
	hl.bind("P", hl.dsp.submap("reset"))
	hl.bind(
		"O",
		hl.dsp.exec_cmd(
			"grimblast save output-| swappy -f- && [[ $(wl-paste -l)==image/png ]] && notify-send Screenshot copied to clipboard"
		)
	)
	hl.bind("O", hl.dsp.submap("reset"))
	hl.bind(
		"SHIFT" .. " + " .. "P",
		hl.dsp.exec_cmd(
			"bash -c 'grimblast save area-| curl -s -F file=@-;filename=.png https://x0.at/| tee >(wl-copy) >(xargs notify-send)'"
		)
	)
	hl.bind("SHIFT" .. " + " .. "P", hl.dsp.submap("reset"))
	hl.bind(
		"SHIFT" .. " + " .. "O",
		hl.dsp.exec_cmd(
			"bash -c 'grimblast save output-| curl -s -F file=@-;filename=.png https://x0.at/| tee >(wl-copy) >(xargs notify-send)'"
		)
	)
	hl.bind("SHIFT" .. " + " .. "O", hl.dsp.submap("reset"))
	hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "R", hl.dsp.submap(" Record (r)+ [Shift for 󰍮]"))

hl.define_submap(" Record (r)+ [Shift for 󰍮]", function()
	hl.bind("R", hl.dsp.exec_cmd("~/.config/waybar/scripts/recorder.sh"))
	hl.bind("R", hl.dsp.submap("reset"))
	hl.bind("SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("~/.config/waybar/scripts/recorder.sh -a"))
	hl.bind("SHIFT" .. " + " .. "R", hl.dsp.submap("reset"))
	hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.bind(mainMod .. " + " .. "escape", hl.dsp.exec_cmd("killall -s SIGINT wf-recorder"))

hl.bind(
	"SUPER" .. " + " .. "V",
	hl.dsp.exec_cmd("cliphist list| rofi -dmenu -p Select item to copy| cliphist decode| wl-copy")
)

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd(terminal))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.window.close())

-- bind = $mainMod, M, exit,

hl.bind(mainMod .. " + " .. "X", hl.dsp.exec_cmd(fileManager))

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd(browser))

hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd(code))

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("~/.config/waybar/scripts/launcher.sh"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("~/.config/waybar/scripts/powermenu.sh"))

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.window.center())

hl.bind(mainMod .. " + " .. "G", hl.dsp.group.toggle())

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd(menu))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- dwindle

hl.bind("CTRL" .. " + " .. "ESCAPE", hl.dsp.exec_cmd("killall waybar || systemctl --user start waybar"))

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("pkill -SIGUSR2 waybar"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("waypaper"))

hl.bind("escape", hl.dsp.exec_cmd("hyprctl dispatch closewindow class:^floating_shell$"), { non_consuming = true })

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Volume and Media Control

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl pause"))

hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"))

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

hl.bind("ALT" .. " + " .. "space", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind("ALT" .. " + " .. "return", hl.dsp.exec_cmd("playerctl stop"))

hl.bind("ALT" .. " + " .. "left", hl.dsp.exec_cmd("playerctl previous"))

hl.bind("ALT" .. " + " .. "right", hl.dsp.exec_cmd("playerctl next"))

hl.bind("ALT" .. " + " .. "up", hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"))

hl.bind("ALT" .. " + " .. "down", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"))

-- Screen brightness

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s +5%"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 5%-"))
